{{- if and .Values.vcsGateway.enabled .Values.vcsGateway.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vcs-gateway
  labels:
    {{- include "spacelift.vcsGatewayLabels" . | nindent 4 }}
  {{- with .Values.vcsGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.vcsGateway.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ required "vcsGateway.domain is required when vcsGateway is enabled" .Values.vcsGateway.domain }}
      secretName: vcs-gateway-cert
  rules:
    - host: {{ .Values.vcsGateway.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spacelift.fullname" $ }}-vcs-gateway
                port:
                  name: grpc
{{- end }}
